/* Auto-generated by genmsg_cpp for file /home/abc/ros_autonavigation_ws/src/autonavigation/msg/WayPoint.msg */
#ifndef AUTONAVIGATION_MESSAGE_WAYPOINT_H
#define AUTONAVIGATION_MESSAGE_WAYPOINT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace autonavigation
{
template <class ContainerAllocator>
struct WayPoint_ {
  typedef WayPoint_<ContainerAllocator> Type;

  WayPoint_()
  : x(0)
  , y(0)
  , z(0)
  {
  }

  WayPoint_(const ContainerAllocator& _alloc)
  : x(0)
  , y(0)
  , z(0)
  {
  }

  typedef int32_t _x_type;
  int32_t x;

  typedef int32_t _y_type;
  int32_t y;

  typedef int32_t _z_type;
  int32_t z;


  typedef boost::shared_ptr< ::autonavigation::WayPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autonavigation::WayPoint_<ContainerAllocator>  const> ConstPtr;
}; // struct WayPoint
typedef  ::autonavigation::WayPoint_<std::allocator<void> > WayPoint;

typedef boost::shared_ptr< ::autonavigation::WayPoint> WayPointPtr;
typedef boost::shared_ptr< ::autonavigation::WayPoint const> WayPointConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::autonavigation::WayPoint_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::autonavigation::WayPoint_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace autonavigation

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::autonavigation::WayPoint_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::autonavigation::WayPoint_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::autonavigation::WayPoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3cb41a2c4416de195dbb95b7777a06fb";
  }

  static const char* value(const  ::autonavigation::WayPoint_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3cb41a2c4416de19ULL;
  static const uint64_t static_value2 = 0x5dbb95b7777a06fbULL;
};

template<class ContainerAllocator>
struct DataType< ::autonavigation::WayPoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "autonavigation/WayPoint";
  }

  static const char* value(const  ::autonavigation::WayPoint_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::autonavigation::WayPoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 x\n\
int32 y\n\
int32 z\n\
\n\
";
  }

  static const char* value(const  ::autonavigation::WayPoint_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::autonavigation::WayPoint_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::autonavigation::WayPoint_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct WayPoint_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autonavigation::WayPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::autonavigation::WayPoint_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.z);
  }
};


} // namespace message_operations
} // namespace ros

#endif // AUTONAVIGATION_MESSAGE_WAYPOINT_H

