# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autonavigation/PathProperty.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import autonavigation.msg

class PathProperty(genpy.Message):
  _md5sum = "e5513d10a16a565d2f690143b65fbdcd"
  _type = "autonavigation/PathProperty"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """WayPoint left_boundary
WayPoint right_boundary
int32    direction


================================================================================
MSG: autonavigation/WayPoint
int32 x
int32 y
int32 z
"""
  __slots__ = ['left_boundary','right_boundary','direction']
  _slot_types = ['autonavigation/WayPoint','autonavigation/WayPoint','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_boundary,right_boundary,direction

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PathProperty, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.left_boundary is None:
        self.left_boundary = autonavigation.msg.WayPoint()
      if self.right_boundary is None:
        self.right_boundary = autonavigation.msg.WayPoint()
      if self.direction is None:
        self.direction = 0
    else:
      self.left_boundary = autonavigation.msg.WayPoint()
      self.right_boundary = autonavigation.msg.WayPoint()
      self.direction = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_7i.pack(_x.left_boundary.x, _x.left_boundary.y, _x.left_boundary.z, _x.right_boundary.x, _x.right_boundary.y, _x.right_boundary.z, _x.direction))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.left_boundary is None:
        self.left_boundary = autonavigation.msg.WayPoint()
      if self.right_boundary is None:
        self.right_boundary = autonavigation.msg.WayPoint()
      end = 0
      _x = self
      start = end
      end += 28
      (_x.left_boundary.x, _x.left_boundary.y, _x.left_boundary.z, _x.right_boundary.x, _x.right_boundary.y, _x.right_boundary.z, _x.direction,) = _struct_7i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_7i.pack(_x.left_boundary.x, _x.left_boundary.y, _x.left_boundary.z, _x.right_boundary.x, _x.right_boundary.y, _x.right_boundary.z, _x.direction))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.left_boundary is None:
        self.left_boundary = autonavigation.msg.WayPoint()
      if self.right_boundary is None:
        self.right_boundary = autonavigation.msg.WayPoint()
      end = 0
      _x = self
      start = end
      end += 28
      (_x.left_boundary.x, _x.left_boundary.y, _x.left_boundary.z, _x.right_boundary.x, _x.right_boundary.y, _x.right_boundary.z, _x.direction,) = _struct_7i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_7i = struct.Struct("<7i")
