# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autonavigation/VelodyneLine.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import autonavigation.msg

class VelodyneLine(genpy.Message):
  _md5sum = "7c8138d92dd21d98965a9487a7b04516"
  _type = "autonavigation/VelodyneLine"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """
VelodynePoint[] velodyneline

================================================================================
MSG: autonavigation/VelodynePoint
# velodyne point 

int16  x             #cm
int16  y            
int16  z
uint16  intensity     #0-255
uint16  angleH        #0.01degree
uint16  angleV        #0.01degree
uint8   ring

"""
  __slots__ = ['velodyneline']
  _slot_types = ['autonavigation/VelodynePoint[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       velodyneline

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VelodyneLine, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.velodyneline is None:
        self.velodyneline = []
    else:
      self.velodyneline = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.velodyneline)
      buff.write(_struct_I.pack(length))
      for val1 in self.velodyneline:
        _x = val1
        buff.write(_struct_3h3HB.pack(_x.x, _x.y, _x.z, _x.intensity, _x.angleH, _x.angleV, _x.ring))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.velodyneline is None:
        self.velodyneline = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.velodyneline = []
      for i in range(0, length):
        val1 = autonavigation.msg.VelodynePoint()
        _x = val1
        start = end
        end += 13
        (_x.x, _x.y, _x.z, _x.intensity, _x.angleH, _x.angleV, _x.ring,) = _struct_3h3HB.unpack(str[start:end])
        self.velodyneline.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.velodyneline)
      buff.write(_struct_I.pack(length))
      for val1 in self.velodyneline:
        _x = val1
        buff.write(_struct_3h3HB.pack(_x.x, _x.y, _x.z, _x.intensity, _x.angleH, _x.angleV, _x.ring))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.velodyneline is None:
        self.velodyneline = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.velodyneline = []
      for i in range(0, length):
        val1 = autonavigation.msg.VelodynePoint()
        _x = val1
        start = end
        end += 13
        (_x.x, _x.y, _x.z, _x.intensity, _x.angleH, _x.angleV, _x.ring,) = _struct_3h3HB.unpack(str[start:end])
        self.velodyneline.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3h3HB = struct.Struct("<3h3HB")
