(cl:in-package autonavigation-msg)
(cl:export '(GPS_FLAG-VAL
          GPS_FLAG
          GPS_WEEK-VAL
          GPS_WEEK
          GPS_MILLISECOND-VAL
          GPS_MILLISECOND
          LONGITUDE-VAL
          LONGITUDE
          LALTITUDE-VAL
          LALTITUDE
          GAUSSX-VAL
          GAUSSX
          GAUSSY-VAL
          GAUSSY
          HEIGHT-VAL
          HEIGHT
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          AZIMUTH-VAL
          AZIMUTH
          NORTHVELOCITY-VAL
          NORTHVELOCITY
          EASTVELOCITY-VAL
          EASTVELOCITY
          UPVELOCITY-VAL
          UPVELOCITY
          POSITIONSTATUS-VAL
          POSITIONSTATUS
          ROT_X-VAL
          ROT_X
          ROT_Y-VAL
          ROT_Y
          ROT_Z-VAL
          ROT_Z
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
))