(cl:in-package autonavigation-msg)
(cl:export '(ACTUALFRONTWHEELANGLE-VAL
          ACTUALFRONTWHEELANGLE
          DESIREDFRONTWHEELANGLE-VAL
          DESIREDFRONTWHEELANGLE
          ACTUALCURVATURE-VAL
          ACTUALCURVATURE
          DESIREDCURVATURE-VAL
          DESIREDCURVATURE
          LEFTLIGHTFLAG-VAL
          LEFTLIGHTFLAG
          RIGHTLIGHTFLAG-VAL
          RIGHTLIGHTFLAG
))