(cl:in-package autonavigation-msg)
(cl:export '(UNIQUE_KEY-VAL
          UNIQUE_KEY
          GPS_WEEK-VAL
          GPS_WEEK
          GPS_MILLISECOND-VAL
          GPS_MILLISECOND
          CMD_MILLISECOND-VAL
          CMD_MILLISECOND
          CMD_STEER-VAL
          CMD_STEER
          CMD_VELOCITY-VAL
          CMD_VELOCITY
          CMD_CURVATURE-VAL
          CMD_CURVATURE
          CMD_FORCE_START-VAL
          CMD_FORCE_START
          CMD_TASK_MODE-VAL
          CMD_TASK_MODE
          CMD_HAND_BRAKE-VAL
          CMD_HAND_BRAKE
          CMD_THROTTLE-VAL
          CMD_THROTTLE
          CMD_BRAKE-VAL
          CMD_BRAKE
          CMD_SHIFT-VAL
          CMD_SHIFT
          CMD_IGNITION-VAL
          CMD_IGNITION
          CMD_LIGHT-VAL
          CMD_LIGHT
          CMD_RESET-VAL
          CMD_RESET
          CMD_RESERVE2-VAL
          CMD_RESERVE2
          CMD_RESERVE3-VAL
          CMD_RESERVE3
))