(cl:in-package autonavigation-msg)
(cl:export '(STEERINGWHEEL-VAL
          STEERINGWHEEL
          CLUTCH-VAL
          CLUTCH
          BRAKE-VAL
          BRAKE
          SASPEDAL-VAL
          SASPEDAL
          SHIFTPADDLESL-VAL
          SHIFTPADDLESL
          SHIFTPADDLESR-VAL
          SHIFTPADDLESR
          IGNITION-VAL
          IGNITION
          HANDBRAKE-VAL
          HANDBRAKE
          STICKSHIFT-VAL
          STICKSHIFT
          CROSSL-VAL
          CROSSL
          CROSSR-VAL
          CROSSR
          MANUALTRANSMISSION-VAL
          MANUALTRANSMISSION
          WHEELFUNCTIONKEY-VAL
          WHEELFUNCTIONKEY
          CONCATENONSIGNAL-VAL
          CONCATENONSIGNAL
          CMD_RESERVE2-VAL
          CMD_RESERVE2
          CMD_RESERVE3-VAL
          CMD_RESERVE3
          CMD_RESERVE4-VAL
          CMD_RESERVE4
          CMD_RESERVE5-VAL
          CMD_RESERVE5
))