(cl:in-package autonavigation-msg)
(cl:export '(UNIQUE_KEY-VAL
          UNIQUE_KEY
          GPS_WEEK-VAL
          GPS_WEEK
          GPS_MILLISECOND-VAL
          GPS_MILLISECOND
          LONGITUDE-VAL
          LONGITUDE
          LATITUDE-VAL
          LATITUDE
          GAUSSX-VAL
          GAUSSX
          GAUSSY-VAL
          GAUSSY
          HEIGHT-VAL
          HEIGHT
          AZIMUTH-VAL
          AZIMUTH
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          NORTHVELOCITY-VAL
          NORTHVELOCITY
          EASTVELOCITY-VAL
          EASTVELOCITY
          UPVELOCITY-VAL
          UPVELOCITY
          TRAVEL_DISTANCE-VAL
          TRAVEL_DISTANCE
          REMAIN_TIME-VAL
          REMAIN_TIME
          TIME_DELAY-VAL
          TIME_DELAY
          STEER-VAL
          STEER
          FUEL-VAL
          FUEL
          SHIFT-VAL
          SHIFT
          VOLTAGE-VAL
          VOLTAGE
          THROTTLE-VAL
          THROTTLE
          BRAKE-VAL
          BRAKE
          ENGINE_SPEED-VAL
          ENGINE_SPEED
          VEHICLE_SPEED-VAL
          VEHICLE_SPEED
          WATER_TEMPERATURE-VAL
          WATER_TEMPERATURE
          CONTROL_STATUS-VAL
          CONTROL_STATUS
          ERROR_STATUS-VAL
          ERROR_STATUS
          BAROMETER1-VAL
          BAROMETER1
          BAROMETER2-VAL
          BAROMETER2
          HANDBRAKE-VAL
          HANDBRAKE
          ENGINE_STATUS-VAL
          ENGINE_STATUS
          STS_MODE-VAL
          STS_MODE
          CONTROLLABLE1-VAL
          CONTROLLABLE1
          ENABLE-VAL
          ENABLE
          RESERVE3-VAL
          RESERVE3
          RESERVE4-VAL
          RESERVE4
          RESERVE5-VAL
          RESERVE5
          RESERVE6-VAL
          RESERVE6
          RESERVE7-VAL
          RESERVE7
          MD5_STR-VAL
          MD5_STR
))