(cl:in-package autonavigation-msg)
(cl:export '(UNIQUE_KEY-VAL
          UNIQUE_KEY
          GPS_WEEK-VAL
          GPS_WEEK
          GPS_MILLISECOND-VAL
          GPS_MILLISECOND
          LONGITUDE-VAL
          LONGITUDE
          LATITUDE-VAL
          LATITUDE
          GAUSSX-VAL
          GAUSSX
          GAUSSY-VAL
          GAUSSY
          AZIMUTH-VAL
          AZIMUTH
          TRAVEL_DISTANCE-VAL
          TRAVEL_DISTANCE
          REMAIN_TIME-VAL
          REMAIN_TIME
          STEER-VAL
          STEER
          FUEL-VAL
          FUEL
          SHIFT-VAL
          SHIFT
          VOLTAGE-VAL
          VOLTAGE
          THROTTLE-VAL
          THROTTLE
          BRAKE-VAL
          BRAKE
          ENGINE_SPEED-VAL
          ENGINE_SPEED
          VEHICLE_SPEED-VAL
          VEHICLE_SPEED
          CONTROL_STATUS-VAL
          CONTROL_STATUS
          HANDBRAKE-VAL
          HANDBRAKE
          ENGINE_STATUS-VAL
          ENGINE_STATUS
          CONTROLLABLE1-VAL
          CONTROLLABLE1
          RESERVE1-VAL
          RESERVE1
          RESERVE2-VAL
          RESERVE2
          RESERVE3-VAL
          RESERVE3
))