/* Auto-generated by genmsg_cpp for file /home/wangyi/rosros_autonavigation_ws/src/autonavigation/msg/EntityKeyPoint.msg */
#ifndef AUTONAVIGATION_MESSAGE_ENTITYKEYPOINT_H
#define AUTONAVIGATION_MESSAGE_ENTITYKEYPOINT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace autonavigation
{
template <class ContainerAllocator>
struct EntityKeyPoint_ {
  typedef EntityKeyPoint_<ContainerAllocator> Type;

  EntityKeyPoint_()
  : x(0)
  , y(0)
  , direction(0)
  , type(0)
  {
  }

  EntityKeyPoint_(const ContainerAllocator& _alloc)
  : x(0)
  , y(0)
  , direction(0)
  , type(0)
  {
  }

  typedef int32_t _x_type;
  int32_t x;

  typedef int32_t _y_type;
  int32_t y;

  typedef int32_t _direction_type;
  int32_t direction;

  typedef int32_t _type_type;
  int32_t type;


  typedef boost::shared_ptr< ::autonavigation::EntityKeyPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autonavigation::EntityKeyPoint_<ContainerAllocator>  const> ConstPtr;
}; // struct EntityKeyPoint
typedef  ::autonavigation::EntityKeyPoint_<std::allocator<void> > EntityKeyPoint;

typedef boost::shared_ptr< ::autonavigation::EntityKeyPoint> EntityKeyPointPtr;
typedef boost::shared_ptr< ::autonavigation::EntityKeyPoint const> EntityKeyPointConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::autonavigation::EntityKeyPoint_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::autonavigation::EntityKeyPoint_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace autonavigation

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::autonavigation::EntityKeyPoint_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::autonavigation::EntityKeyPoint_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::autonavigation::EntityKeyPoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7a9140b1be6ec243afada729627b204c";
  }

  static const char* value(const  ::autonavigation::EntityKeyPoint_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7a9140b1be6ec243ULL;
  static const uint64_t static_value2 = 0xafada729627b204cULL;
};

template<class ContainerAllocator>
struct DataType< ::autonavigation::EntityKeyPoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "autonavigation/EntityKeyPoint";
  }

  static const char* value(const  ::autonavigation::EntityKeyPoint_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::autonavigation::EntityKeyPoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 x\n\
int32 y\n\
int32 direction   #  0-36000，道路方向\n\
int32 type        #  0: 当前路口， 1: 左出口点， 2：右出口点， 3： 直行出口点\n\
\n\
\n\
";
  }

  static const char* value(const  ::autonavigation::EntityKeyPoint_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::autonavigation::EntityKeyPoint_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::autonavigation::EntityKeyPoint_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.direction);
    stream.next(m.type);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct EntityKeyPoint_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autonavigation::EntityKeyPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::autonavigation::EntityKeyPoint_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "direction: ";
    Printer<int32_t>::stream(s, indent + "  ", v.direction);
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
  }
};


} // namespace message_operations
} // namespace ros

#endif // AUTONAVIGATION_MESSAGE_ENTITYKEYPOINT_H

