(cl:in-package autonavigation-msg)
(cl:export '(HEAD-VAL
          HEAD
          LOCALPOSE-VAL
          LOCALPOSE
          GPSPOS-VAL
          GPSPOS
          VEHICLENUM-VAL
          VEHICLENUM
          VEHICLES-VAL
          VEHICLES
          VEHICLELANE-VAL
          VEHICLELANE
          PEDESTRIANNUM-VAL
          PEDESTRIANNUM
          PEDESTRIANS-VAL
          PEDESTRIANS
          PEDESTRIANLANE-VAL
          PEDESTRIANLANE
          LANENUM-VAL
          LANENUM
          LANES-VAL
          LANES
          CURRENTLANE-VAL
          CURRENTLANE
          FAROBJECTNUM-VAL
          FAROBJECTNUM
          FARSTATICOBJECTS-VAL
          FARSTATICOBJECTS
          KEYPOINTS-VAL
          KEYPOINTS
          KEYPOINTNUM-VAL
          KEYPOINTNUM
          PARKSPACE-VAL
          PARKSPACE
          PARKSPACENUM-VAL
          PARKSPACENUM
          ROADMARKINGNUM-VAL
          ROADMARKINGNUM
          ROADMARKINGS-VAL
          ROADMARKINGS
          SIGNNUM-VAL
          SIGNNUM
          SIGNS-VAL
          SIGNS
          LIGHTNUM-VAL
          LIGHTNUM
          LIGHTS-VAL
          LIGHTS
))