(cl:in-package autonavigation-msg)
(cl:export '(UNIQUE_KEY-VAL
          UNIQUE_KEY
          GPS_WEEK-VAL
          GPS_WEEK
          GPS_MILLISECOND-VAL
          GPS_MILLISECOND
          CMD_MILLISECOND-VAL
          CMD_MILLISECOND
          CMD_PRIORITY-VAL
          CMD_PRIORITY
          CMD_TASK_MODE-VAL
          CMD_TASK_MODE
          CMD_HAND_BRAKE-VAL
          CMD_HAND_BRAKE
          CMD_THROTTLE-VAL
          CMD_THROTTLE
          CMD_BRAKE-VAL
          CMD_BRAKE
          CMD_SHIFT-VAL
          CMD_SHIFT
          CMD_IGNITION-VAL
          CMD_IGNITION
          CMD_LIGHT-VAL
          CMD_LIGHT
          CMD_RESERVE1-VAL
          CMD_RESERVE1
          CMD_RESERVE2-VAL
          CMD_RESERVE2
          CMD_RESERVE3-VAL
          CMD_RESERVE3
          CMD_RESERVE4-VAL
          CMD_RESERVE4
          CMD_RESERVE5-VAL
          CMD_RESERVE5
          CMD_RESERVE6-VAL
          CMD_RESERVE6
          CMD_RESERVE7-VAL
          CMD_RESERVE7
          CMD_RESERVE8-VAL
          CMD_RESERVE8
))