(cl:in-package autonavigation-msg)
(cl:export '(HEAD-VAL
          HEAD
          LOCALPOSE-VAL
          LOCALPOSE
          GPSPOS-VAL
          GPSPOS
          PLAN_DATA_ID-VAL
          PLAN_DATA_ID
          PLAN_FRAME-VAL
          PLAN_FRAME
          PLANOUTPUTMODE-VAL
          PLANOUTPUTMODE
          IS_OK-VAL
          IS_OK
          EFFECTIVE_POINT_NUM-VAL
          EFFECTIVE_POINT_NUM
          PATH-VAL
          PATH
          PATH_PROPERTY-VAL
          PATH_PROPERTY
          VEHICLE_COMMAND-VAL
          VEHICLE_COMMAND
          SYS_STATE-VAL
          SYS_STATE
          PLAN_STATE-VAL
          PLAN_STATE
          SPEED-VAL
          SPEED
          VEHICLE2FLO-VAL
          VEHICLE2FLO
          POINT2STOP-VAL
          POINT2STOP
          EXPVELOCITY-VAL
          EXPVELOCITY
          EXPCURVATURE-VAL
          EXPCURVATURE
))